# Generated by Django 5.0 on 2024-01-08 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateTimeField(auto_now_add=True)),
                ('text_transcript', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NlpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('model_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speechdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechassistantapp.speechdata')),
            ],
        ),
    ]
